version: 0.0
os: linux
files:
    - source: /
      destination: /zignaly/{directory}
hooks:
    AfterInstall:
        - location: scripts/after_install.sh
          runas: root
          timeout: 600