version: 0.0
os: linux
files:
    - source: /
      destination: /zignaly/{directory}/deploy
hooks:
    BeforeInstall:
        - location: scripts/prepare_release.sh
          timeout: 300
          runas: root
    AfterInstall:
        - location: scripts/after_install.sh
          runas: root
          timeout: 600